---
- name: download latest dokuwiki
  get_url:
    url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki-stable.tgz
- name: unarchive dokuwiki-stable.tgz to /srv/dokuwiki
  unarchive:
    src: /tmp/dokuwiki-stable.tgz
    dest: /srv/
    owner: www-data
    remote_src: yes
    list_files: yes
  register: file_list

- name: remove stupid version name from folder path
  file:
    src: /srv/{{ file_list['files'][0] }}
    dest: /srv/dokuwiki
    owner: www-data
    state: link

- name: Install xml-php package used by dokuwiki.
  apt:
    name: php7.0-xml
  when: ansible_pkg_mgr == "apt"
