---
- name: Check whether dokuwiki is already installed
  stat:
    path: "{{ dokuwiki_install_path }}"
  register: dokuwiki_dir_exists

- import_tasks: install.yml
  when: not dokuwiki_dir_exists.stat.exists

- import_tasks: update.yml
  when: dokuwiki_dir_exists.stat.exists

- import_tasks: configure.yml
