---
- unarchive:
    src: /files/{{ dokuwiki_filename }}
    dest: /dokuwiki/

- name: Create local.php config file
  template:
    src: templates/local.php.j2
    dest: /dokuwiki/conf/local.php.dist
