---
- name: Download latest dokuwiki
  get_url:
    url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki-stable.tgz

- name: Create tmp dir for dokuwiki
  file:
    state: directory
    path: /tmp/dokuwiki

- name: Unarchive dokuwiki-stable.tgz to /tmp/dokuwiki
  unarchive:
    src: /tmp/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki
    owner: www-data
    remote_src: yes
    list_files: yes
  register: file_list

- name: Get stats from new version file
  stat:
    path: "/tmp/dokuwiki/{{file_list.files[0]}}VERSION"
  register: new_version

- name: Get stats from old version file
  stat:
    path: "{{dokuwiki_install_path}}/VERSION"
  register: old_version

- name: Unarchive dokuwiki-stable.tgz to {{ dokuwiki_install_path }}
  unarchive:
    src: /tmp/dokuwiki-stable.tgz
    dest: "{{ dokuwiki_install_path | dirname }}"
    owner: www-data
    remote_src: yes
    list_files: yes
  when: new_version.stat.checksum != old_version.stat.checksum

