---
- name: download latest dokuwiki
  get_url:
    url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki-stable.tgz
 
- name: unarchive dokuwiki-stable.tgz to /srv/dokuwiki
  unarchive:
    src: /tmp/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki
    owner: www-data
    remote_src: yes
    list_files: yes
  register: file_list

- name: unarchive dokuwiki-stable.tgz to {{ dokuwiki_install_path }}
  unarchive:
    src: /tmp/dokuwiki
    dest: "{{ dokuwiki_install_path | dirname }}"
    owner: www-data
    remote_src: yes
    list_files: yes
  when: "{{ lookup('file', '/tmp/dokuwiki/VERSION')  != lookup('file', '{{ dokuwiki_install_path }}/VERSION') }}"

- debug: msg="{{ file_list }}"